// <auto-generated />
using AnimalHouseApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalHouseApi.Migrations
{
    [DbContext(typeof(AnimalHouseApiContext))]
    [Migration("20230331193230_hopeigoteverything")]
    partial class hopeigoteverything
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalHouseApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.Property<string>("SubSpecies")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 1,
                            Name = "Goji",
                            Species = "Dog",
                            SubSpecies = "Pitbull"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 1,
                            Name = "Darryl",
                            Species = "Dog",
                            SubSpecies = "Australian Cattle Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 6,
                            Name = "ChopSticks",
                            Species = "Cat",
                            SubSpecies = "Siamese"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 2,
                            Name = "FuzzyWasHe",
                            Species = "Cat",
                            SubSpecies = "Persian"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 3,
                            Name = "Olaf",
                            Species = "Dog",
                            SubSpecies = "Wolfhound"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 3,
                            Name = "Tuna",
                            Species = "Cat",
                            SubSpecies = "Snowshoe"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 2,
                            Name = "Shark",
                            Species = "Dog",
                            SubSpecies = "Pitbull"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 2,
                            Name = "Bologna",
                            Species = "Dog",
                            SubSpecies = "Pitbull"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 2,
                            Name = "Steeze",
                            Species = "Cat",
                            SubSpecies = "Abyssinian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
